enableScripts: true
yarnPath: ".yarn/releases/yarn-berry.cjs"
cacheFolder: "./.yarn/cache"

#
#이걸 활성화 하고 언플러그드에 다 집어 넣기
#supportedArchitectures: {
#                            List of operating systems to cover.
#
#    os: [
#        "current",
#        "darwin",
#        "linux",
#        "win32",
#    ],
#                            List of CPU architectures to cover.
#
#                            See https://nodejs.org/docs/latest/api/process.html#processarch for the architectures supported by Node.js
#
#    cpu: [
#        "current",
#        "x64",
#        "ia32",
#        "arm64",
#    ],
#                            The list of standard C libraries to cover.
#
#    libc: [
#        "current",
#        "glibc",
#        "musl",
#    ],
#},
